name = "EspyInsideFunction"
uuid = "d6b55740-5cb4-11ec-1cb9-93db9984c461"
authors = ["Philippe Maincon <philippe.maincon@sintef.no>"]
version = "0.1.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.6"
