name = "EspyInsideFunction"
uuid = "2b54c6b0-5ccd-11ec-2d73-45d62642ee81"
authors = ["Philippe Maincon <philippe.maincon@sintef.no>"]
version = "0.1.1"

[compat]
julia = "1.6"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
